#!/bin/bash
# MotionEye Webhook Configuration Script
# Generated automatically - run this script to see configuration instructions

WEBHOOK_URL="http://localhost:8001/api/motioneye/webhook"
WEBHOOK_CMD="curl -X POST http://localhost:8001/api/motioneye/webhook -F file_path=%f -F camera_id=%c"

echo "============================================================"
echo "MotionEye Webhook Configuration"
echo "============================================================"
echo ""
echo "Webhook URL: $WEBHOOK_URL"
echo "Webhook Command: $WEBHOOK_CMD"
echo ""
echo "Total cameras: 13"
echo ""
echo "For each camera, add this to 'on_picture_save' in MotionEye:"
echo "$WEBHOOK_CMD"
echo ""
echo "Cameras to configure:"
echo "  - Camera 1: WYZECAM2-03"
echo "  - Camera 2: wyzecam3-03"
echo "  - Camera 3: WYZECAM2-01"
echo "  - Camera 4: WYZECAM2-02"
echo "  - Camera 5: wyzecam3-04"
echo "  - Camera 6: WYZECAM3-02"
echo "  - Camera 7: esp01"
echo "  - Camera 8: WYZECAM3-01"
echo "  - Camera 9: Camera9"
echo "  - Camera 10: Camera10"
echo "  - Camera 11: Camera11"
echo "  - Camera 12: Camera12"
echo "  - Camera 13: AMB82-001"

echo ""
echo "To configure manually:"
echo "1. Open MotionEye: http://localhost:8765"
echo "2. For each camera listed above:"
echo "   - Click on the camera"
echo "   - Go to 'Motion Detection' settings"
echo "   - Find 'on_picture_save' field"
echo "   - Paste the webhook command"
echo "   - Save settings"
echo ""
