# MotionEye Webhook Configuration Script
# Generated automatically - run this script to see configuration instructions

$WEBHOOK_URL = "http://localhost:8001/api/motioneye/webhook"
$WEBHOOK_CMD = "curl -X POST http://localhost:8001/api/motioneye/webhook -F file_path=%f -F camera_id=%c"

Write-Host "============================================================"
Write-Host "MotionEye Webhook Configuration"
Write-Host "============================================================"
Write-Host ""
Write-Host "Webhook URL: $WEBHOOK_URL"
Write-Host "Webhook Command: $WEBHOOK_CMD"
Write-Host ""
Write-Host "Total cameras: 13"
Write-Host ""
Write-Host "For each camera, add this to 'on_picture_save' in MotionEye:"
Write-Host $WEBHOOK_CMD
Write-Host ""
Write-Host "Cameras to configure:"
Write-Host "  - Camera 1: WYZECAM2-03"
Write-Host "  - Camera 2: wyzecam3-03"
Write-Host "  - Camera 3: WYZECAM2-01"
Write-Host "  - Camera 4: WYZECAM2-02"
Write-Host "  - Camera 5: wyzecam3-04"
Write-Host "  - Camera 6: WYZECAM3-02"
Write-Host "  - Camera 7: esp01"
Write-Host "  - Camera 8: WYZECAM3-01"
Write-Host "  - Camera 9: Camera9"
Write-Host "  - Camera 10: Camera10"
Write-Host "  - Camera 11: Camera11"
Write-Host "  - Camera 12: Camera12"
Write-Host "  - Camera 13: AMB82-001"

Write-Host ""
Write-Host "To configure manually:"
Write-Host "1. Open MotionEye: http://localhost:8765"
Write-Host "2. For each camera listed above:"
Write-Host "   - Click on the camera"
Write-Host "   - Go to 'Motion Detection' settings"
Write-Host "   - Find 'on_picture_save' field"
Write-Host "   - Paste the webhook command"
Write-Host "   - Save settings"
Write-Host ""
Write-Host "Press any key to open MotionEye in your browser..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
Start-Process "http://localhost:8765"
